// src/pages/KOL/KOLList.vue
<template>
  <div class="kol-list">
    <el-page-header @back="false" content="达人列表" />
    
    <!-- 搜索和筛选 -->
    <el-card class="search-card">
      <el-form :model="searchForm" :inline="true">
        <el-form-item label="搜索">
          <el-input
            v-model="searchForm.search"
            placeholder="搜索达人名称"
            clearable
            style="width: 200px"
          />
        </el-form-item>
        <el-form-item label="平台">
          <el-select
            v-model="searchForm.platform"
            placeholder="选择平台"
            clearable
            style="width: 120px"
          >
            <el-option label="抖音" value="tiktok" />
            <el-option label="小红书" value="xiaohongshu" />
            <el-option label="微博" value="weibo" />
            <el-option label="B站" value="bilibili" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch">搜索</el-button>
          <el-button @click="resetSearch">重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 达人列表 -->
    <el-card class="list-card">
      <template #header>
        <div class="card-header">
          <span>达人列表 ({{ total }})</span>
          <el-button type="primary" @click="handleImport">
            <el-icon><Plus /></el-icon>
            导入达人
          </el-button>
        </div>
      </template>
      
      <el-table
        :data="kolList"
        v-loading="loading"
        style="width: 100%"
      >
        <el-table-column label="达人信息" min-width="200">
          <template #default="{ row }">
            <div class="kol-info">
              <el-avatar
                :src="row.avatar"
                :size="40"
                class="avatar"
              >
                {{ row.name.charAt(0) }}
              </el-avatar>
              <div class="info">
                <div class="name">{{ row.name }}</div>
                <div class="tags">
                  <el-tag
                    v-for="tag in row.tags"
                    :key="tag"
                    size="small"
                    type="info"
                  >
                    {{ tag }}
                  </el-tag>
                </div>
              </div>
            </div>
          </template>
        </el-table-column>
        
        <el-table-column prop="platform" label="平台" width="100">
          <template #default="{ row }">
            <el-tag :type="getPlatformType(row.platform)">
              {{ getPlatformName(row.platform) }}
            </el-tag>
          </template>
        </el-table-column>
        
        <el-table-column prop="followerCount" label="粉丝数" width="120">
          <template #default="{ row }">
            {{ formatNumber(row.followerCount) }}
          </template>
        </el-table-column>
        
        <el-table-column prop="likeCount" label="点赞数" width="120">
          <template #default="{ row }">
            {{ formatNumber(row.likeCount) }}
          </template>
        </el-table-column>
        
        <el-table-column prop="totalWorks" label="作品数" width="100" />
        
        <el-table-column prop="createdAt" label="创建时间" width="180">
          <template #default="{ row }">
            {{ formatTime(row.createdAt) }}
          </template>
        </el-table-column>
        
        <el-table-column label="操作" width="180">
          <template #default="{ row }">
            <el-button type="text" size="small" @click="viewDetail(row)">
              查看详情
            </el-button>
            <el-button type="text" size="small" @click="viewWorks(row)">
              查看作品
            </el-button>
            <el-button type="text" size="small" @click="editKOL(row)">
              编辑
            </el-button>
          </template>
        </el-table-column>
      </el-table>
      
      <!-- 分页 -->
      <el-pagination
        v-model:current-page="pagination.page"
        v-model:page-size="pagination.pageSize"
        :page-sizes="[10, 20, 50, 100]"
        :total="total"
        layout="total, sizes, prev, pager, next, jumper"
        style="margin-top: 20px; text-align: right"
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
      />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import dayjs from 'dayjs'
import type { KOL } from '@/types'

const router = useRouter()

// 响应式数据
const loading = ref(false)
const kolList = ref<KOL[]>([])
const total = ref(0)

const searchForm = reactive({
  search: '',
  platform: ''
})

const pagination = reactive({
  page: 1,
  pageSize: 20
})

// 方法
const fetchKOLList = async () => {
  loading.value = true
  try {
    // TODO: 从API获取达人列表
    // 模拟数据
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    kolList.value = [
      {
        id: '1',
        name: '美食博主小王',
        platform: 'xiaohongshu',
        profileUrl: 'https://example.com',
        avatar: 'https://example.com/avatar1.jpg',
        description: '专注美食分享',
        followerCount: 125000,
        likeCount: 980000,
        totalWorks: 234,
        tags: ['美食', '生活'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: '2',
        name: '科技达人小李',
        platform: 'tiktok',
        profileUrl: 'https://example.com',
        followerCount: 89000,
        likeCount: 567000,
        totalWorks: 156,
        tags: ['科技', '数码'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }
    ]
    
    total.value = 2
  } catch (error) {
    console.error('获取达人列表失败:', error)
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  pagination.page = 1
  fetchKOLList()
}

const resetSearch = () => {
  searchForm.search = ''
  searchForm.platform = ''
  handleSearch()
}

const handleSizeChange = (size: number) => {
  pagination.pageSize = size
  fetchKOLList()
}

const handleCurrentChange = (page: number) => {
  pagination.page = page
  fetchKOLList()
}

const handleImport = () => {
  router.push('/import')
}

const getPlatformName = (platform: string) => {
  const names: Record<string, string> = {
    tiktok: '抖音',
    xiaohongshu: '小红书',
    weibo: '微博',
    bilibili: 'B站',
    other: '其他'
  }
  return names[platform] || platform
}

const getPlatformType = (platform: string): 'primary' | 'success' | 'warning' | 'info' | 'danger' => {
  const types: Record<string, 'primary' | 'success' | 'warning' | 'info' | 'danger'> = {
    tiktok: 'primary',
    xiaohongshu: 'danger',
    weibo: 'warning',
    bilibili: 'info',
    other: 'info'
  }
  return types[platform] || 'info'
}

const formatNumber = (num: number) => {
  if (num >= 10000) {
    return (num / 10000).toFixed(1) + 'w'
  }
  return num.toLocaleString()
}

const formatTime = (time: string) => {
  return dayjs(time).format('YYYY-MM-DD HH:mm')
}

const viewDetail = (kol: KOL) => {
  ElMessage.info('查看详情功能开发中...')
}

const viewWorks = (kol: KOL) => {
  router.push({ path: '/works-list', query: { kolId: kol.id } })
}

const editKOL = (kol: KOL) => {
  ElMessage.info('编辑功能开发中...')
}

// 生命周期
onMounted(() => {
  fetchKOLList()
})
</script>

<style scoped>
.kol-list {
  max-width: 1200px;
}

.search-card {
  margin: 20px 0;
}

.list-card {
  margin: 20px 0;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.kol-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.info .name {
  font-weight: 500;
  margin-bottom: 4px;
}

.info .tags {
  display: flex;
  gap: 4px;
}
</style>

// src/pages/KOL/KOLList.tsx
import React, { useState, useEffect } from 'react'
import {
  Card,
  Table,
  Button,
  Input,
  Select,
  Space,
  Tag,
  Avatar,
  Typography,
  Tooltip,
  message,
  Row,
  Col,
  Statistic,
} from 'antd'
import {
  SearchOutlined,
  ExportOutlined,
  EyeOutlined,
  FilterOutlined,
  ReloadOutlined,
} from '@ant-design/icons'
import type { ColumnsType, TableProps } from 'antd/es/table'
import * as XLSX from 'xlsx'
import type { KOL, QueryParams } from '@/types'

const { Text } = Typography

const KOLList: React.FC = () => {
  const [loading, setLoading] = useState(false)
  const [dataSource, setDataSource] = useState<KOL[]>([])
  const [filteredData, setFilteredData] = useState<KOL[]>([])
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([])
  const [queryParams, setQueryParams] = useState<QueryParams>({
    page: 1,
    pageSize: 10,
    sortBy: 'createdAt',
    sortOrder: 'desc',
  })

  useEffect(() => {
    fetchKOLList()
  }, [queryParams])

  const fetchKOLList = async () => {
    setLoading(true)
    try {
      // 模拟API调用
      await new Promise(resolve => setTimeout(resolve, 800))
      
      // 模拟数据
      const mockData: KOL[] = [
        {
          id: '1',
          name: '美食博主小王',
          platform: 'xiaohongshu',
          profileUrl: 'https://example.com/user1',
          avatar: 'https://example.com/avatar1.jpg',
          description: '专注分享美食制作技巧和生活美学',
          followerCount: 125000,
          likeCount: 980000,
          totalWorks: 234,
          tags: ['美食', '生活', '烘焙'],
          createdAt: '2024-01-15T10:30:00Z',
          updatedAt: '2024-01-20T14:20:00Z',
        },
        {
          id: '2',
          name: '旅行达人Lisa',
          platform: 'tiktok',
          profileUrl: 'https://example.com/user2',
          followerCount: 89000,
          likeCount: 650000,
          totalWorks: 156,
          tags: ['旅行', '摄影'],
          createdAt: '2024-01-12T09:15:00Z',
          updatedAt: '2024-01-18T16:45:00Z',
        },
        {
          id: '3',
          name: '时尚穿搭师',
          platform: 'weibo',
          profileUrl: 'https://example.com/user3',
          followerCount: 203000,
          likeCount: 1250000,
          totalWorks: 445,
          tags: ['时尚', '穿搭', '美妆'],
          createdAt: '2024-01-10T15:22:00Z',
          updatedAt: '2024-01-19T11:30:00Z',
        },
      ]
      
      setDataSource(mockData)
      setFilteredData(mockData)
    } catch (error) {
      message.error('获取达人列表失败')
    } finally {
      setLoading(false)
    }
  }

  const handleSearch = (value: string) => {
    const filtered = dataSource.filter(kol =>
      kol.name.toLowerCase().includes(value.toLowerCase()) ||
      kol.tags.some(tag => tag.toLowerCase().includes(value.toLowerCase()))
    )
    setFilteredData(filtered)
  }

  const handlePlatformFilter = (platform: string) => {
    if (platform === 'all') {
      setFilteredData(dataSource)
    } else {
      const filtered = dataSource.filter(kol => kol.platform === platform)
      setFilteredData(filtered)
    }
  }

  const handleExport = () => {
    const exportData = (selectedRowKeys.length > 0 
      ? filteredData.filter(kol => selectedRowKeys.includes(kol.id))
      : filteredData
    ).map(kol => ({
      '达人名称': kol.name,
      '平台': getPlatformText(kol.platform),
      '粉丝数': kol.followerCount,
      '点赞数': kol.likeCount,
      '作品数': kol.totalWorks,
      '标签': kol.tags.join(', '),
      '主页链接': kol.profileUrl,
      '创建时间': new Date(kol.createdAt).toLocaleString(),
    }))

    const ws = XLSX.utils.json_to_sheet(exportData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, '达人列表')
    XLSX.writeFile(wb, `达人列表_${new Date().toISOString().split('T')[0]}.xlsx`)
    
    message.success('导出成功')
  }

  const getPlatformText = (platform: string) => {
    const platformMap = {
      xiaohongshu: '小红书',
      tiktok: '抖音',
      weibo: '微博',
      bilibili: 'B站',
      other: '其他',
    }
    return platformMap[platform as keyof typeof platformMap] || platform
  }

  const getPlatformColor = (platform: string) => {
    const colorMap = {
      xiaohongshu: '#ff2442',
      tiktok: '#000000',
      weibo: '#e6162d',
      bilibili: '#00a1d6',
      other: '#666666',
    }
    return colorMap[platform as keyof typeof colorMap] || '#666666'
  }

  const formatNumber = (num: number) => {
    if (num >= 10000) {
      return `${(num / 10000).toFixed(1)}万`
    }
    return num.toLocaleString()
  }

  const columns: ColumnsType<KOL> = [
    {
      title: '达人信息',
      dataIndex: 'name',
      key: 'name',
      width: 250,
      render: (_, record) => (
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <Avatar
            src={record.avatar}
            size={40}
            style={{ marginRight: 12, flexShrink: 0 }}
          >
            {record.name.charAt(0)}
          </Avatar>
          <div style={{ minWidth: 0 }}>
            <div style={{ fontWeight: 'bold', marginBottom: 4 }}>
              {record.name}
            </div>
            <Tag color={getPlatformColor(record.platform)} size="small">
              {getPlatformText(record.platform)}
            </Tag>
          </div>
        </div>
      ),
    },
    {
      title: '粉丝数',
      dataIndex: 'followerCount',
      key: 'followerCount',
      width: 120,
      sorter: (a, b) => a.followerCount - b.followerCount,
      render: (value) => formatNumber(value),
    },
    {
      title: '点赞数',
      dataIndex: 'likeCount',
      key: 'likeCount',
      width: 120,
      sorter: (a, b) => a.likeCount - b.likeCount,
      render: (value) => formatNumber(value),
    },
    {
      title: '作品数',
      dataIndex: 'totalWorks',
      key: 'totalWorks',
      width: 100,
      sorter: (a, b) => a.totalWorks - b.totalWorks,
    },
    {
      title: '标签',
      dataIndex: 'tags',
      key: 'tags',
      width: 200,
      render: (tags: string[]) => (
        <div>
          {tags.slice(0, 2).map(tag => (
            <Tag key={tag} size="small" style={{ marginBottom: 2 }}>
              {tag}
            </Tag>
          ))}
          {tags.length > 2 && (
            <Tooltip title={tags.slice(2).join(', ')}>
              <Tag size="small" style={{ marginBottom: 2 }}>
                +{tags.length - 2}
              </Tag>
            </Tooltip>
          )}
        </div>
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 150,
      sorter: (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
      render: (value) => new Date(value).toLocaleDateString(),
    },
    {
      title: '操作',
      key: 'action',
      width: 100,
      render: (_, record) => (
        <Space>
          <Tooltip title="查看详情">
            <Button
              type="link"
              icon={<EyeOutlined />}
              onClick={() => window.open(record.profileUrl, '_blank')}
            />
          </Tooltip>
        </Space>
      ),
    },
  ]

  const rowSelection: TableProps<KOL>['rowSelection'] = {
    selectedRowKeys,
    onChange: setSelectedRowKeys,
  }

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <Typography.Title level={2}>达人列表</Typography.Title>
        <Text type="secondary">管理和查看所有导入的达人数据</Text>
      </div>

      {/* 统计卡片 */}
      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col span={6}>
          <Card>
            <Statistic title="总达人数" value={dataSource.length} />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic 
              title="平均粉丝数" 
              value={dataSource.length > 0 
                ? Math.round(dataSource.reduce((sum, kol) => sum + kol.followerCount, 0) / dataSource.length)
                : 0
              }
              formatter={(value) => formatNumber(Number(value))}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic 
              title="总作品数" 
              value={dataSource.reduce((sum, kol) => sum + kol.totalWorks, 0)}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card>
            <Statistic title="选中数量" value={selectedRowKeys.length} />
          </Card>
        </Col>
      </Row>

      {/* 操作栏 */}
      <Card style={{ marginBottom: 24 }}>
        <Row gutter={[16, 16]} align="middle">
          <Col xs={24} sm={12} md={8}>
            <Input.Search
              placeholder="搜索达人名称或标签"
              allowClear
              onSearch={handleSearch}
              style={{ width: '100%' }}
            />
          </Col>
          <Col xs={24} sm={12} md={6}>
            <Select
              placeholder="选择平台"
              allowClear
              style={{ width: '100%' }}
              onChange={handlePlatformFilter}
            >
              <Select.Option value="all">全部平台</Select.Option>
              <Select.Option value="xiaohongshu">小红书</Select.Option>
              <Select.Option value="tiktok">抖音</Select.Option>
              <Select.Option value="weibo">微博</Select.Option>
              <Select.Option value="bilibili">B站</Select.Option>
            </Select>
          </Col>
          <Col xs={24} md={10}>
            <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
              <Button
                icon={<ReloadOutlined />}
                onClick={fetchKOLList}
                loading={loading}
              >
                刷新
              </Button>
              <Button
                type="primary"
                icon={<ExportOutlined />}
                onClick={handleExport}
                disabled={filteredData.length === 0}
              >
                导出Excel
              </Button>
            </Space>
          </Col>
        </Row>
      </Card>

      {/* 数据表格 */}
      <Card>
        <Table
          columns={columns}
          dataSource={filteredData}
          rowKey="id"
          loading={loading}
          rowSelection={rowSelection}
          pagination={{
            current: queryParams.page,
            pageSize: queryParams.pageSize,
            total: filteredData.length,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total, range) => 
              `第 ${range[0]}-${range[1]} 条，共 ${total} 条`,
            onChange: (page, pageSize) => 
              setQueryParams(prev => ({ ...prev, page, pageSize })),
          }}
          scroll={{ x: 1200 }}
        />
      </Card>
    </div>
  )
}

export default KOLList
